apiVersion: cloudflare.cloudflare.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: cloudflare
      namespace: crossplane-system
      key: credentials
